version: "3.7"

services:
   
  #Distributed Tracing
  #http://localhost:9411/
  zipkin-server:
    image: openzipkin/zipkin:2.23.2
    ports:
      - 9411:9411
    networks:
      - stack1-network  

  #DataBase 1
  postgres_cambio:
    container_name: postgres_cambio_service
    image: postgres:12.2
    environment:
      DATABASE_HOST: localhost
      POSTGRES_DB: cambio_service
      POSTGRES_USER: cambio
      POSTGRES_PASSWORD: cambio
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped      
    networks:
      - stack1-network
    
  #DataBase 2
  postgres_book:
    container_name: postgres_book_service
    image: postgres:12.2
    environment:
      DATABASE_HOST: localhost
      POSTGRES_DB: book_service
      POSTGRES_USER: book
      POSTGRES_PASSWORD: book
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_2_init.sql
    ports:
      - "5433:5432"
    restart: unless-stopped
    networks:
      - stack1-network
      
  #Eureka Server
  #http://localhost:8761/
  naming-server:
    image: carlosmedeiroslima/naming-server:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    networks:
      - stack1-network
      
  #Api Gateway
  api-gateway:
    image: carlosmedeiroslima/api-gateway:0.0.1-SNAPSHOT
    ports:
      - 8765:8765
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
    networks:
      - stack1-network
      
  #Cambio Service
  cambio-service:
    image: carlosmedeiroslima/cambio-service:0.0.1-SNAPSHOT
    restart: always
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      SPRING.DATASOURCE.URL: jdbc:postgresql://postgres_cambio:5432/cambio_service
      SPRING.DATASOURCE.USERNAME: cambio
      SPRING.DATASOURCE.PASSWORD: cambio
    ports:
      - 8000:8000
    depends_on:
      - naming-server
      - postgres_cambio
    networks:
      - stack1-network
      
  #Book Service
  book-service:
    image: carlosmedeiroslima/book-service:0.0.1-SNAPSHOT
    restart: always
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      SPRING.DATASOURCE.URL: jdbc:postgresql://postgres_book:5432/cambio_service
      SPRING.DATASOURCE.USERNAME: book
      SPRING.DATASOURCE.PASSWORD: book
    ports:
      - 8100:8100
    depends_on:
      - naming-server
      - postgres_book
    networks:
      - stack1-network
      


networks:
  stack1-network:
    driver: bridge  
    
    
 